name: Update Frontend
on:
  push:
    branches:
      - main
env: 
  AWS_REGION: us-east-1
permissions: 
  id-token: write
  contents: read
jobs:
  pre_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14.3'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: ensure browsers are installed
        run: python -m playwright install --with-deps
      - name: serve site locally
        run: python -m http.server 8000 --directory site &
      - name: run tests
        run: pytest tests/test_static.py --tracing=retain-on-failure
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/      
  build:
    needs: pre_test
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: ${{ secrets.SERVICE_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: install Terraform
        uses: hashicorp/setup-terraform@v4.0.0
      - name: build with Terraform  
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
      - name: upload to the bucket
        run: |
          aws s3 sync site/ s3://$(cd terraform && terraform output -raw s3_bucket_name)
      - name: invalidate cloudfront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $(cd terraform && terraform output -raw cloudfront_distribution_id) \
            --paths "/index.html" "/styles.css"
  post_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14.3'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: ensure browsers are installed
        run: python -m playwright install --with-deps
      - name: serve site locally
        run: python -m http.server 8000 --directory site &
      - name: run tests
        run: pytest tests/test_live.py --tracing=retain-on-failure
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/ 